CREATE DATABASE smarthome;

\c smarthome;

CREATE TABLE users (
  ID SERIAL PRIMARY KEY,
  username VARCHAR(25) UNIQUE NOT NULL,
  password CHAR(64) NOT NULL
);

CREATE TABLE raspberry_pi (
  ID SERIAL PRIMARY KEY,
  USER_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES users(ID)
);

CREATE TABLE gadget_type (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(50)
);

CREATE TABLE gadgets (
  ID SERIAL PRIMARY KEY,
  PI_ID INT NOT NULL,
  GADGET_TYPE_ID INT NOT NULL,
  PIN_ID INT NOT NULL,
  POWER INT NOT NULL,
  STATUS BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (PI_ID) REFERENCES raspberry_pi(ID),
  FOREIGN KEY (GADGET_TYPE_ID) REFERENCES gadget_type(ID)
);

CREATE TABLE scheduled_tasks (
  GADGET_ID INT NOT NULL,
  SCHEDULED_TIME TIMESTAMPTZ NOT NULL,
  TASK_TO_DO BOOLEAN NOT NULL,
  STATUS VARCHAR(20),
  FOREIGN KEY (GADGET_ID) REFERENCES gadgets(ID)
);

CREATE TABLE session (
  GADGET_ID INT NOT NULL,
  STARTING_DATETIME TIMESTAMPTZ NOT NULL,
  ENDING_TIME TIMESTAMPTZ,
  FOREIGN KEY (GADGET_ID) REFERENCES gadgets(ID)
);

DROP TABLE session;
DROP TABLE scheduled_tasks;
DROP TABLE gadgets;
DROP TABLE gadget_type;
DROP TABLE raspberry_pi;
DROP TABLE users;