# Generated by Django 2.2.2 on 2019-06-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaspBerryPi', '0002_auto_20190628_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
