# Generated by Django 2.2.2 on 2019-06-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaspBerryPi', '0003_auto_20190628_1236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
