# Generated by Django 2.2.2 on 2019-06-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaspBerryPi', '0004_auto_20190628_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledTasks',
        ),
    ]
