# Generated by Django 2.2.2 on 2019-06-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaspBerryPi', '0007_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name_plural': 'Users'},
        ),
    ]
